#!/usr/bin/env bash

# initial convert README.md to asciidoc
## $ pandoc -s --wrap=preserve -f gfm -t asciidoc README.md -o readme.adoc

## create docbook/docbook5 xml
asciidoctor -b docbook -a leveloffset=+1 -a hardbreaks -a wrap=preserve readme.adoc

rm -f README-NEW.md
iconv -t utf-8 readme.xml | pandoc -s -f docbook --wrap=preserve -t gfm+smart+space_in_atx_header | iconv -f utf-8 > README-NEW.md

echo '<!-- Don't change this file! It's autogenerated from readme.adoc -->' | cat - README-NEW.md > README.md
